# Example inventory with default values only.

[privx_primary]

[privx_additional_nodes]

[privxextender]

[privxcarrier]

[privxwebproxy]

[all:vars]
privx_ips=""
privx_superuser=admin
email_domain=example.com
database_name=privx
database_username=privx
database_port=5432
database_sslmode=require
postgres_ssl_cert_file=./privx-db-trust-anchor.pem
manage_ssh_product_repo=true
manage_epel_repo=true
manage_docker_ce_repo=true
manage_postgresql_module=true
custom_ssh_product_repo_url=
custom_ssh_product_repo_file=
ssh_product_repo_gpg_key_url=https://product-repository.ssh.com/info.fi-ssh.com-pubkey.asc
ansible_user=rocky
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
